# fly.toml app configuration file generated for auto-bot-notification on 2024-11-26T21:40:43+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auto-bot-notification'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
